#!/bin/bash

set -e

if [ -z "$1" ]; then
	printf 'ERROR: no gluon-release was specified.\n' >&2
		exit 1
fi


if ! [ -f "./gluon" ]; then
	printf 'ERROR: "./gluon"-file could not be found in wd, please cwd to the right directory.\n' >&2
	exit 1
fi

. ./gluon

sel_gluon_release="$1"
selected_found=0

opwd=$(pwd)

for GluonRelease in $GLUON_RELEASES; do
	if ! [ "$GluonRelease" == "$sel_gluon_release" ]; then
		continue
	else
		selected_found=1
	fi
done

if [ "$selected_found" -ne "1" ]; then
	printf 'ERROR: "$sel_gluon_release" could not be found in ./gluon file.\n' >&2
	exit 1
fi


if ! [ -d "$GluonRelease-repo-patches" ]; then
	printf 'WARN: No repo-patches found.\n' >&2
	exit 0
fi

cd "$GluonRelease"

patchdir="$opwd/$GluonRelease-repo-patches"

for dir in $(find "$patchdir/" -type d || printf 'WARN: No patchsets found.\n' >&2 && exit 0); do
	if [ "$patchdir/" == "$dir" ]; then
		continue
	fi
	for patch in $(find "$dir" -type f >/dev/null 2>&1 || printf "WARN: No patches in patchset $(echo $dir | rev | cut -d / -f 1 | rev) found.\n" >&2 ); do
		git checkout -B patching base

		if ! git -c user.name='Gluon Patch Manager' -c user.email='gluon@void.example.com' -c commit.gpgsign=false am --whitespace=nowarn --committer-date-is-author-date "$patchdir/$dir/$patch"; then
			git am --abort
			git checkout patched
			git branch -D patching
			exit 1
		fi
	done
done
git branch -M patched
