#!/bin/bash

# parameter 1: templatefolder
# parameter 2: all-folder
# parameter 3: destination folder

if [ -z "$1" ]; then
        printf 'ERROR: no templatefolder was specified.\n' >&2
    exit 1
elif ! [ -d "$1" ]; then
        printf 'ERROR: templatefolder was not found on filesystem.\n' >&2
    exit 1
fi


if [ -z "$2" ]; then
        printf 'ERROR: no all-folder was specified.\n' >&2
    exit 1
elif ! [ -d "$2" ]; then
        printf 'ERROR: all-folder was not found on filesystem.\n' >&2
    exit 1
fi


if [ -z "$3" ]; then
        printf 'ERROR: no destination folder was specified.\n' >&2
    exit 1
elif ! [ -d "$2" ]; then
        printf 'ERROR: destination folder was not found on filesystem.\n' >&2
    exit 1
fi

# step 1copy all to destination folder
if [ "${$2:-1}" == "/" ];l

# step 2 copy templates with no-template names to folder
# step 3 copy subdirectory for community to folder
# step 4 apply vars via sed to template-files
# step 5 remove vars file
