#!/bin/bash

set -e

DIR="$(pwd)"

sel_gluon_release="$1"
if [ -z "$sel_gluon_release" ]; then
	printf 'ERROR: no gluon-release was specified.\n' >&2
	exit 1
fi

SITE="$2"
if [ -z "$SITE" ]; then
	printf 'no site selected, set site via second parameter'>&2
	exit 1
fi


if ! [ -f './gluon' ]; then
	printf 'ERROR: "./gluon"-file could not be found in wd, please cwd to the right directory.\n' >&2
	exit 1
fi

. ./gluon

selected_found=0

for GluonRelease in $GLUON_RELEASES; do
	if ! [ "$GluonRelease" == "$sel_gluon_release" ]; then
		continue
	else
		selected_found=1
		break
	fi
done

if [ "$selected_found" -ne "1" ]; then
	printf 'ERROR: "$sel_gluon_release" could not be found in ./gluon file.\n' >&2
	exit 1
fi


if [ ! -d "$GluonRelease" ]; then
	printf 'ERROR: Gluon-Folder could not be located.\n' >&2
	exit 1
fi

echo "fetching sites-repo..."
. ./get-sites
cd "$DIR"

template_folder="./site-modules/$(echo $SITE|cut -d '/' -f1)/$sel_gluon_release/$(echo $SITE|cut -d '/' -f2)"
all_folder="./site-modules/$(echo $SITE|cut -d '/' -f1)/$sel_gluon_release/all"

if [ -z "$template_folder" ]; then
    printf 'ERROR: no templatefolder was specified.\n' >&2
    exit 1
elif ! [ -d "$template_folder" ]; then
    printf 'ERROR: selected site ($SITE) not found.\n' >&2
    exit 1
fi

if [ -z "$all_folder" ]; then
    printf 'ERROR: no all-folder was specified.\n' >&2
    exit 1
elif ! [ -d "$all_folder" ]; then
    printf 'ERROR: all-folder was not found on filesystem.\n' >&2
    exit 1
fi

# step 1  copy all to destination folder
rm -fR "./$GluonRelease/site/"
mkdir -p "./$GluonRelease/site/"
cp -ax "$all_folder/"* "./$GluonRelease/site/"

# step 2 copy templates with no-template names to destination folder
mkdir -p "./$GluonRelease/site/i18n/"
mv "./$GluonRelease/site/de.po.template" "./$GluonRelease/site/i18n/de.po"
mv "./$GluonRelease/site/en.po.template" "./$GluonRelease/site/i18n/en.po"
mv "./$GluonRelease/site/site.conf.template" "./$GluonRelease/site/site.conf"

# step 3 copy subdirectory for community to folder
cp -ax "$template_folder/"* "./$GluonRelease/site/"

# step 4 apply vars via sed to template-files

vars=("sitename" "sitecode" "city" "city2" "domain" "prefix4" "prefix6" "ntpserver" "ssid" "meshmac" "meshid" "ip4nn" "ip6nn" "fastdmethods" "fastdmtu" "fastdpeergroups" "updateprobability" "pubkeys" "updateprobabilityrc")

. "./$GluonRelease/site/vars"

for e in ${vars[@]}; do
    sed -i -e "s/+++$e+++/$(echo ${!e} | sed 's/\//\\\//g')/" "./$GluonRelease/site/site.conf"
    sed -i -e "s/+++$e+++/$(echo ${!e} | sed 's/\//\\\//g')/" "./$GluonRelease/site/i18n/de.po"
    sed -i -e "s/+++$e+++/$(echo ${!e} | sed 's/\//\\\//g')/" "./$GluonRelease/site/i18n/en.po"
done


# step 5 remove vars file
rm -f "./$GluonRelease/site/vars"

cat "./$sel_gluon_release-version" >> "./$GluonRelease/site/site.mk"
echo "Site generated: $SITE"

cd "$DIR"
